source: source/index.js
dist: dist/feedback.js

bfPlugins:
  - name: errorify
  - name: browserify-banner
    options:
      file: dist/feedback.js
      template: "<%= pkg.name %> v<%= pkg.version %>\n<%= pkg.url %>\n<%= pkg.author.name %>\n<%= moment().year() %>"
      pkg:
        name: 'InSalesFeedback'
        version: '0.15.13'
        url: https://github.com/VladimirIvanin/InSalesFeedback
        author:
          name: 'Vladimir Ivanin'

bfTransforms:
  - name: eslintify
    options:
      passthrough: [ 'errors', 'warnings' ]
  - name: jstify
    options:
      engine: global
  - name: uglifyify
    options:
      sourceMap: false
